### PR TITLE
Fix lints

### LINKED ISSUE #304: 'Yivi meetup' link on more tab links to a non-existing page
The 'Yivi meetup' information is not on the Yivi website anymore. In the app there is still a link to the old website. The link currently just returns the Yivi homepage.

### LINKED ISSUE #311: Fix tech debt
The Flutter code has some tech debt that should be dealt with. 
You can get a list of problems by running `flutter analyze`.

### PR DESCRIPTION
**Pull request by w-ensink**
Builds on #310 
Aims to fix #311 
Also fixes #304 
Also works around #313 by disabling Impeller on Android

One warning about the `keyshareAttribute` remains, because fixing that would require updating the format of the scheme, which is too big a task for now.

### CODE REVIEW

File: lib/app.dart [hunk 1]
```diff
@@ -127,6 +128,13 @@ class AppState extends State<App> with WidgetsBindingObserver {
     }
   }
 
+  @override
+  void didChangeDependencies() {
+    super.didChangeDependencies();
+    final repo = IrmaRepositoryProvider.of(context);
```
Comment (w-ensink) [inline lib/app.dart:134]: This should be only initialized once

File: lib/src/screens/activity/activity_tab.dart [hunk 2]
```diff
@@ -42,6 +45,12 @@ class _ActivityTabState extends State<ActivityTab> {
     });
   }
 
+  @override
+  void didChangeDependencies() {
+    super.didChangeDependencies();
+    _historyRepo = HistoryRepository(IrmaRepositoryProvider.of(context));
```
Comment (w-ensink) [inline lib/src/screens/activity/activity_tab.dart:51]: Maybe this only needs to happen once?

File: lib/src/screens/pin/session_pin_screen.dart [hunk 3]
```diff
@@ -58,6 +57,13 @@ class _SessionPinScreenState extends State<SessionPinScreen> with WidgetsBinding
     });
   }
 
+  @override
+  void didChangeDependencies() {
```
Comment (w-ensink) [inline lib/src/screens/pin/session_pin_screen.dart:61]: Consider this may happen multiple times

File: lib/app.dart [hunk 4]
```diff
@@ -204,14 +217,12 @@ class AppState extends State<App> with WidgetsBindingObserver {
...
           return MaterialPageRoute(
             builder: (BuildContext context) {
-              return WillPopScope(
-                onWillPop: () async {
-                  // On the pinscreen, background instead of pop
+              return PopScope(
+                canPop: settings.name != PinScreen.routeName,
+                onPopInvokedWithResult: (didPop, popResult) {
+                  // On the pin screen, background instead of pop
                   if (settings.name == PinScreen.routeName) {
```
Comment (jappe999) [inline lib/app.dart:224]: `didPop` can be reused here, right? Something like this:

```suggestion
                  if (!didPop) {
```

File: lib/src/data/irma_client_bridge.dart [hunk 5]
```diff
@@ -91,7 +91,13 @@ class IrmaClientBridge extends IrmaBridge {
       }
 
       if (debugLogging) {
-        debugPrint('Received bridge event: ${call.method} with payload ${call.arguments}');
+        // the irma config event has so much data in its payload it bloats all logs,
+        // therefore we explicitly don't print the payload
+        if (call.method == 'IrmaConfigurationEvent') {
```
Comment (jappe999) [inline lib/src/data/irma_client_bridge.dart:96]: Do we need it for debugging, though?

File: lib/src/data/irma_preferences.dart [hunk 6]
```diff
@@ -98,34 +54,74 @@ class IrmaPreferences {
...
 
+  // Used to store all notifications
+  static const String _serializedNotificationsKey = 'preference.notifications';
+  final Preference<String> _serializedNotifications;
+
+  // =============================================================================
+
+  Stream<bool> getScreenshotsEnabled() => _screenshotsEnabled;
+
+  Future<bool> setScreenshotsEnabled(bool value) => _screenshotsEnabled.setValue(value);
```
Comment (jappe999) [inline lib/src/data/irma_preferences.dart:75]: Isn't it easier to read if the variables are grouped together?

**Review by jappe999 — COMMENTED** [review]
Awesome changes! Just a few questions :)

File: lib/app.dart (hunk 4 above)
Comment (w-ensink) [reply lib/app.dart:224]: Yes good spot. I used to have it that way, but it caused issues on Android.. Maybe I'll take a closer look.

File: lib/src/data/irma_client_bridge.dart (hunk 5 above)
Comment (w-ensink) [reply lib/src/data/irma_client_bridge.dart:96]: I haven't needed it so far. It only bloated the logs so much that the other, more important logging was not visible anymore. It prints like a thousand lines all at once and does that multiple times and pretty much none of it has been relevant to me so far.

File: lib/src/models/session.dart [hunk 7]
```diff
@@ -125,25 +125,17 @@ class SessionPointer implements Pointer {
...
 
   factory SessionPointer.fromJson(Map<String, dynamic> json) => _$SessionPointerFromJson(json);
   Map<String, dynamic> toJson() => _$SessionPointerToJson(this);
 
   @override
-  Future<void> validate({required IrmaRepository irmaRepository, RequestorInfo? requestor}) async {
-    // Check whether returnURL is valid.
-    if (returnURL != null) Uri.parse(returnURL!);
-  }
+  Future<void> validate({required IrmaRepository irmaRepository, RequestorInfo? requestor}) async {}
```
[the remark this answers is not in the document]
Comment (w-ensink) [reply lib/src/models/session.dart:138]: Will look into that. It is defined by the parent class, so I couldn't remove it easily.

File: lib/src/screens/pin/session_pin_screen.dart [hunk 8]
```diff
@@ -58,6 +57,18 @@ class _SessionPinScreenState extends State<SessionPinScreen> with WidgetsBinding
...
+    super.didChangeDependencies();
+    // only init _repo once...
+    try {
+      _repo;
+    } catch (_) {
+      _repo = IrmaRepositoryProvider.of(context);
+      _pinBloc = PinBloc(_repo);
+    }
```
[the remark this answers is not in the document]
Comment (w-ensink) [reply lib/src/screens/pin/session_pin_screen.dart:69]: It is definitely a hack, but I haven't found a cleaner way. The problem is the way this repo has been set up, so this is mainly here for legacy reasons. We can't use `initState()`, because the BuildContext is not available here, but we can't set the _pinBloc variable multiple times either, because that starts listening to a stream and it would do that multiple times if we didn't use this hack...

This will definitely need a refactor on a deeper level in the future.

File: lib/src/screens/session/disclosure/disclosure_permission.dart [hunk 9]
```diff
@@ -67,22 +67,22 @@ class ProvidedDisclosurePermission extends StatelessWidget {
         ? onConfirmedDismiss()
         : DisclosurePermissionCloseDialog.show(context, onConfirm: onConfirmedDismiss);
 
-    // Wrapped with WillPopScope to gain control over the behavior of the "go back" gesture
-    return WillPopScope(
-      onWillPop: () async {
+    // Wrapped with PopScope to gain control over the behavior of the "go back" gesture
+    // Wrapped with PopScope to gain control over the behavior of the "go back" gesture
```
[the remark this answers is not in the document]
Comment (w-ensink) [reply lib/src/screens/session/disclosure/disclosure_permission.dart:71]: Good catch!

File: lib/src/screens/session/session_screen.dart [hunk 10]
```diff
@@ -67,15 +74,20 @@ class _SessionScreenState extends State<SessionScreen> {
...
 
-  void _dispatchSessionEvent(SessionEvent event, {bool isBridgedEvent = true}) =>
-      _repo.dispatch(event, isBridgedEvent: isBridgedEvent);
+  // void _dispatchSessionEvent(SessionEvent event, {bool isBridgedEvent = true}){
+  //   if (isBridgedEvent) {
+  //     _repo.bridgedDispatch(event);
+  //   } else {
+  //     _repo.dispatch(event);
+  //   }
+  // }
```
[the remark this answers is not in the document]
Comment (w-ensink) [reply lib/src/screens/session/session_screen.dart:83]: Probably!

File: android/app/src/main/AndroidManifest.xml [hunk 11]
```diff
@@ -6,7 +6,10 @@
          In most cases you can leave this as-is, but you if you want to provide
          additional functionality it is fine to subclass or reimplement
          FlutterApplication and put your custom class here. -->
-    <application
+    <application>
+        <meta-data
+          android:name="io.flutter.embedding.android.EnableImpeller"
+          android:value="false" />
```
[the remark this answers is not in the document]
Comment (w-ensink) [reply android/app/src/main/AndroidManifest.xml:12]: Yes, Impeller on Android renders a black square in the middle of the QR code scanner view finder

File: lib/src/data/irma_preferences.dart (hunk 6 above)
Comment (w-ensink) [reply lib/src/data/irma_preferences.dart:75]: Do you mean like removing line 74 or like putting the `_screenshotsEnabled` var together with these methods?

File: lib/src/models/session.dart (hunk 7 above)
[the remark this answers is not in the document]
Comment (w-ensink) [reply lib/src/models/session.dart:138]: The `validate()` function is defined by the `Pointer` base class and the `IssueWizzardPointer` implements this in a meaningful way. Therefore we can't really remove it and leaving it empty is probably the best way to deal with it for now.

File: lib/src/data/irma_preferences.dart (hunk 6 above)
Comment (w-ensink) [reply lib/src/data/irma_preferences.dart:75]: I personally don't like putting the variables besides these methods, because it makes it harder to get an overview of all the variables that are in these preferences. These getters and setters are a trivial, unimportant detail that just reduce the readability in my opinion.

Comment (jappe999) [reply lib/src/data/irma_preferences.dart:75]: Ah, okay. It's fine either way but I was wondering what the reason behind it was. Thanks for the explanation! :smile

File: lib/app.dart (hunk 4 above)
Comment (jappe999) [reply lib/app.dart:224]: It's not that important to do extensive research. If you find a fix for it, it would be nice though.

Comment (w-ensink) [reply lib/app.dart]: Apparently it's not an issue (anymore), so I made it `!didPop` like you suggested  :-) 
Thanks for the review!

**Review by jappe999 — APPROVED** [review]
🙏

File: lib/src/screens/session/session_screen.dart [hunk 12]
```diff
@@ -39,13 +40,19 @@ class SessionScreen extends StatefulWidget {
...
 
   @override
   void initState() {
     super.initState();
+  }
+
+  @override
+  void didChangeDependencies() {
+    super.didChangeDependencies();
+    _repo = IrmaRepositoryProvider.of(context);
```
Comment (ivard) [inline lib/src/screens/session/session_screen.dart:55]: Here the issue might occur again that `_repo` is initialised twice.

**Review by ivard — CHANGES_REQUESTED** [review]

File: lib/src/screens/session/session_screen.dart (hunk 12 above)
Comment (w-ensink) [reply lib/src/screens/session/session_screen.dart:55]: Good catch! I removed the `final` modifier for the `_repo` field.

**Review by jappe999 — APPROVED** [review]

**Review by ivard — APPROVED** [review]
